//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSag.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiToken
    {
        public int ApiTokenID { get; set; }
        public string ApiTokenName { get; set; }
        public string ApiTokenPass { get; set; }
        public string ApiName { get; set; }
        public Nullable<int> ApiEstado { get; set; }
    }
}
