//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSag.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaTipoDenuncia
    {
        public int idCatTipoDenuncia { get; set; }
        public int idTipoDenuncia { get; set; }
        public int idCategoria { get; set; }
        public bool estado { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual TipoDenuncia TipoDenuncia { get; set; }
    }
}
