//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSag.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DenunciaCategoria
    {
        public int idDenunciaCategoria { get; set; }
        public int idCategoriaTipoDen { get; set; }
        public int idDenuncia { get; set; }
        public Nullable<bool> anonimo { get; set; }
    
        public virtual CategoriaTipoDenuncia CategoriaTipoDenuncia { get; set; }
        public virtual Denuncia Denuncia { get; set; }
    }
}
