//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSag.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Denuncia
    {
        public int IdDenuncia { get; set; }
        public Nullable<int> IdEstadoDenuncia { get; set; }
        public string Descripcion { get; set; }
        public string CorreoContacto { get; set; }
        public string TelefonoContacto { get; set; }
        public System.DateTime FechaEnvio { get; set; }
        public string MensajeVoz { get; set; }
        public string ImagenUrl { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public Nullable<int> idSubCategoria { get; set; }
        public string Comuna { get; set; }
        public string Region { get; set; }
        public string Georeferencia { get; set; }
    
        public virtual EstadoDenuncia EstadoDenuncia { get; set; }
        public virtual SubCategoria SubCategoria { get; set; }
    }
}
