//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Denuncia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class DenunciaCategoria
    {
        public int IdDenuncia { get; set; }
        public int IdTipoDenuncia { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdSubCategoria { get; set; }
    
        public virtual Denuncia Denuncia { get; set; }
        public virtual TipoDenuncia TipoDenuncia { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual SubCategoria SubCategoria { get; set; }
    }
}
