//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Denuncia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class DenunciaGeoReferencia
    {
        public int IdDenunciaGeoReferencia { get; set; }
        public int IdDenuncia { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
    
        public virtual Denuncia Denuncia { get; set; }
    }
}
